global:
  scrape_interval:     15s
  external_labels:
    monitor: 'trillian'

scrape_configs:
  - job_name: 'trillian'
    static_configs:
    - targets: ['localhost:8091']
    # other targets can be added here.
    # this can be automated if a discovery tool is contributed.
    # See #948 for some context.
  - job_name: 'etcd'
    static_configs:
    - targets: ['localhost:2379']
  - job_name: 'prometheus'
    static_configs:
    - targets: ['localhost:9090']

