run:
  timeout: 90s

linters-settings:
  gocyclo:
    min-complexity: 25
  depguard:
    rules:
      main:
        deny:
          - pkg: "^golang.org/x/net/context$"
          - pkg: "github.com/gogo/protobuf/proto"
          - pkg: "encoding/asn1"
          - pkg: "crypto/x509"

issues:
  exclude-use-default: false
  exclude-rules:
    # The following grpc linters are excluded because grpc.Dial, grpc.DialContext and grpc.WithBlock will be supported throughout 1.x.
    - linters: [staticcheck]
      text: 'SA1019: grpc.Dial is deprecated: use NewClient instead'
    - linters: [staticcheck]
      text: 'SA1019: grpc.DialContext is deprecated: use NewClient instead'
    - linters: [staticcheck]
      text: 'SA1019: grpc.WithBlock is deprecated: this DialOption is not supported by NewClient'

  exclude-files:
    - (^|/)x509($|/)
    - (^|/)x509util($|/)
    - (^|/)asn1($|/)
