run:
  deadline: 90s
  skip-dirs:
    - (^|/)x509($|/)
    - (^|/)x509util($|/)
    - (^|/)asn1($|/)

linters-settings:
  gocyclo:
    min-complexity: 25
  depguard:
    list-type: blacklist
    packages:
      - ^golang.org/x/net/context$
      - github.com/gogo/protobuf/proto
      - encoding/asn1
      - crypto/x509

issues:
  exclude-use-default: false
  exclude-rules:
    # The following grpc linters are excluded because grpc.Dial and grpc.DialContext will be supported throughout 1.x.
    - linters: [staticcheck]
      text: 'SA1019: grpc.Dial is deprecated: use NewClient instead'
    - linters: [staticcheck]
      text: 'SA1019: grpc.DialContext is deprecated: use NewClient instead'
