version: '3'
services:
  web:
    build: .
    ports:
      - "5000:5000"
services:
  source:
    build: .
    image: ps4ct
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      # So you don't have to use root, but you can if you like
      #MYSQL_USER: 'user'
      # You can use whatever password you like
      #MYSQL_PASSWORD: 'password'
      # Password for root access
      #MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted


