// Code generated by protoc-gen-go. DO NOT EDIT.
// source: config.proto

package configpb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import any "github.com/golang/protobuf/ptypes/any"
import timestamp "github.com/golang/protobuf/ptypes/timestamp"
import keyspb "github.com/google/trillian/crypto/keyspb"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type LogBackend struct {
	// name defines the name of the log backend for use in LogConfig messages and must be unique.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// backend_spec defines the RPC endpoint that clients should use to send requests
	// to this log backend. These should be in the same format as rpcBackendFlag in the
	// CTFE main and must not be an empty string.
	BackendSpec          string   `protobuf:"bytes,2,opt,name=backend_spec,json=backendSpec,proto3" json:"backend_spec,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogBackend) Reset()         { *m = LogBackend{} }
func (m *LogBackend) String() string { return proto.CompactTextString(m) }
func (*LogBackend) ProtoMessage()    {}
func (*LogBackend) Descriptor() ([]byte, []int) {
	return fileDescriptor_config_6fd5b9e353af6845, []int{0}
}
func (m *LogBackend) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogBackend.Unmarshal(m, b)
}
func (m *LogBackend) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogBackend.Marshal(b, m, deterministic)
}
func (dst *LogBackend) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogBackend.Merge(dst, src)
}
func (m *LogBackend) XXX_Size() int {
	return xxx_messageInfo_LogBackend.Size(m)
}
func (m *LogBackend) XXX_DiscardUnknown() {
	xxx_messageInfo_LogBackend.DiscardUnknown(m)
}

var xxx_messageInfo_LogBackend proto.InternalMessageInfo

func (m *LogBackend) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *LogBackend) GetBackendSpec() string {
	if m != nil {
		return m.BackendSpec
	}
	return ""
}

// LogBackendSet supports a configuration where a single set of frontends handle
// requests for multiple backends. For example this could be used to run different
// backends in different geographic regions.
type LogBackendSet struct {
	Backend              []*LogBackend `protobuf:"bytes,1,rep,name=backend,proto3" json:"backend,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *LogBackendSet) Reset()         { *m = LogBackendSet{} }
func (m *LogBackendSet) String() string { return proto.CompactTextString(m) }
func (*LogBackendSet) ProtoMessage()    {}
func (*LogBackendSet) Descriptor() ([]byte, []int) {
	return fileDescriptor_config_6fd5b9e353af6845, []int{1}
}
func (m *LogBackendSet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogBackendSet.Unmarshal(m, b)
}
func (m *LogBackendSet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogBackendSet.Marshal(b, m, deterministic)
}
func (dst *LogBackendSet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogBackendSet.Merge(dst, src)
}
func (m *LogBackendSet) XXX_Size() int {
	return xxx_messageInfo_LogBackendSet.Size(m)
}
func (m *LogBackendSet) XXX_DiscardUnknown() {
	xxx_messageInfo_LogBackendSet.DiscardUnknown(m)
}

var xxx_messageInfo_LogBackendSet proto.InternalMessageInfo

func (m *LogBackendSet) GetBackend() []*LogBackend {
	if m != nil {
		return m.Backend
	}
	return nil
}

// LogConfigSet is a set of LogConfig messages.
type LogConfigSet struct {
	Config               []*LogConfig `protobuf:"bytes,1,rep,name=config,proto3" json:"config,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *LogConfigSet) Reset()         { *m = LogConfigSet{} }
func (m *LogConfigSet) String() string { return proto.CompactTextString(m) }
func (*LogConfigSet) ProtoMessage()    {}
func (*LogConfigSet) Descriptor() ([]byte, []int) {
	return fileDescriptor_config_6fd5b9e353af6845, []int{2}
}
func (m *LogConfigSet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogConfigSet.Unmarshal(m, b)
}
func (m *LogConfigSet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogConfigSet.Marshal(b, m, deterministic)
}
func (dst *LogConfigSet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogConfigSet.Merge(dst, src)
}
func (m *LogConfigSet) XXX_Size() int {
	return xxx_messageInfo_LogConfigSet.Size(m)
}
func (m *LogConfigSet) XXX_DiscardUnknown() {
	xxx_messageInfo_LogConfigSet.DiscardUnknown(m)
}

var xxx_messageInfo_LogConfigSet proto.InternalMessageInfo

func (m *LogConfigSet) GetConfig() []*LogConfig {
	if m != nil {
		return m.Config
	}
	return nil
}

// LogConfig describes the configuration options for a log instance.
//
// NEXT_ID: 15
type LogConfig struct {
	// The ID of a Trillian tree that stores the log data. The tree type must be
	// LOG for regular CT logs. For mirror logs it must be either PREORDERED_LOG
	// or LOG, and can change at runtime. CTFE in mirror mode uses only read API
	// which is common for both types.
	LogId int64 `protobuf:"varint,1,opt,name=log_id,json=logId,proto3" json:"log_id,omitempty"`
	// prefix is the name of the log. It will come after the global or
	// override handler prefix. For example if the handler prefix is "/logs"
	// and prefix is "vogon" the get-sth handler for this log will be
	// available at "/logs/vogon/ct/v1/get-sth". The prefix cannot be empty
	// and must not include "/" path separator characters.
	Prefix string `protobuf:"bytes,2,opt,name=prefix,proto3" json:"prefix,omitempty"`
	// override_handler_prefix if set to a non empty value overrides the global
	// handler prefix for an individual log. For example this field is set to
	// "/otherlogs" then a log with prefix "vogon" will make it's get-sth handler
	// available at "/otherlogs/vogon/ct/v1/get-sth" regardless of what the
	// global prefix is. Can be set to '/' to make the get-sth handler register
	// at "/vogon/ct/v1/get-sth".
	OverrideHandlerPrefix string `protobuf:"bytes,13,opt,name=override_handler_prefix,json=overrideHandlerPrefix,proto3" json:"override_handler_prefix,omitempty"`
	// Paths to the files containing root certificates that are acceptable to the
	// log. The certs are served through get-roots endpoint. Optional in mirrors.
	RootsPemFile []string `protobuf:"bytes,3,rep,name=roots_pem_file,json=rootsPemFile,proto3" json:"roots_pem_file,omitempty"`
	// The private key used for signing STHs etc. Not required for mirrors.
	PrivateKey *any.Any `protobuf:"bytes,4,opt,name=private_key,json=privateKey,proto3" json:"private_key,omitempty"`
	// The public key matching the above private key (if both are present). It is
	// used only by mirror logs for verifying the source log's signatures, but can
	// be specified for regular logs as well for the convenience of test tools.
	PublicKey *keyspb.PublicKey `protobuf:"bytes,5,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	// If reject_expired is true then the certificate validity period will be
	// checked against the current time during the validation of submissions.
	// This will cause expired certificates to be rejected.
	RejectExpired bool `protobuf:"varint,6,opt,name=reject_expired,json=rejectExpired,proto3" json:"reject_expired,omitempty"`
	// If set, ext_key_usages will restrict the set of such usages that the
	// server will accept. By default all are accepted. The values specified
	// must be ones known to the x509 package.
	ExtKeyUsages []string `protobuf:"bytes,7,rep,name=ext_key_usages,json=extKeyUsages,proto3" json:"ext_key_usages,omitempty"`
	// not_after_start defines the start of the range of acceptable NotAfter
	// values, inclusive.
	// Leaving this unset implies no lower bound to the range.
	NotAfterStart *timestamp.Timestamp `protobuf:"bytes,8,opt,name=not_after_start,json=notAfterStart,proto3" json:"not_after_start,omitempty"`
	// not_after_limit defines the end of the range of acceptable NotAfter values,
	// exclusive.
	// Leaving this unset implies no upper bound to the range.
	NotAfterLimit *timestamp.Timestamp `protobuf:"bytes,9,opt,name=not_after_limit,json=notAfterLimit,proto3" json:"not_after_limit,omitempty"`
	// accept_only_ca controls whether or not *only* certificates with the CA bit
	// set will be accepted.
	AcceptOnlyCa bool `protobuf:"varint,10,opt,name=accept_only_ca,json=acceptOnlyCa,proto3" json:"accept_only_ca,omitempty"`
	// backend_name if set indicates which backend serves this log. The name must be
	// one of those defined in the LogBackendSet.
	LogBackendName string `protobuf:"bytes,11,opt,name=log_backend_name,json=logBackendName,proto3" json:"log_backend_name,omitempty"`
	// If set, the log is a mirror, i.e. it serves the data of another (source)
	// log. It doesn't handle write requests (add-chain, etc.), so it's not a
	// fully fledged RFC-6962 log, but the tree read requests like get-entries and
	// get-consistency-proof are compatible. A mirror doesn't have the source
	// log's key and can't sign STHs. Consequently, the log operator must ensure
	// to channel source log's STHs into CTFE.
	IsMirror bool `protobuf:"varint,12,opt,name=is_mirror,json=isMirror,proto3" json:"is_mirror,omitempty"`
	// dns_zone is the full zone that will be used to query the log via DNS.
	// For example: rocketeer.ct.googleapis.com (without a trailing '.'). If
	// not set then DNS queries will not be served for this log.
	DnsZone              string   `protobuf:"bytes,14,opt,name=dns_zone,json=dnsZone,proto3" json:"dns_zone,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogConfig) Reset()         { *m = LogConfig{} }
func (m *LogConfig) String() string { return proto.CompactTextString(m) }
func (*LogConfig) ProtoMessage()    {}
func (*LogConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_config_6fd5b9e353af6845, []int{3}
}
func (m *LogConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogConfig.Unmarshal(m, b)
}
func (m *LogConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogConfig.Marshal(b, m, deterministic)
}
func (dst *LogConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogConfig.Merge(dst, src)
}
func (m *LogConfig) XXX_Size() int {
	return xxx_messageInfo_LogConfig.Size(m)
}
func (m *LogConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_LogConfig.DiscardUnknown(m)
}

var xxx_messageInfo_LogConfig proto.InternalMessageInfo

func (m *LogConfig) GetLogId() int64 {
	if m != nil {
		return m.LogId
	}
	return 0
}

func (m *LogConfig) GetPrefix() string {
	if m != nil {
		return m.Prefix
	}
	return ""
}

func (m *LogConfig) GetOverrideHandlerPrefix() string {
	if m != nil {
		return m.OverrideHandlerPrefix
	}
	return ""
}

func (m *LogConfig) GetRootsPemFile() []string {
	if m != nil {
		return m.RootsPemFile
	}
	return nil
}

func (m *LogConfig) GetPrivateKey() *any.Any {
	if m != nil {
		return m.PrivateKey
	}
	return nil
}

func (m *LogConfig) GetPublicKey() *keyspb.PublicKey {
	if m != nil {
		return m.PublicKey
	}
	return nil
}

func (m *LogConfig) GetRejectExpired() bool {
	if m != nil {
		return m.RejectExpired
	}
	return false
}

func (m *LogConfig) GetExtKeyUsages() []string {
	if m != nil {
		return m.ExtKeyUsages
	}
	return nil
}

func (m *LogConfig) GetNotAfterStart() *timestamp.Timestamp {
	if m != nil {
		return m.NotAfterStart
	}
	return nil
}

func (m *LogConfig) GetNotAfterLimit() *timestamp.Timestamp {
	if m != nil {
		return m.NotAfterLimit
	}
	return nil
}

func (m *LogConfig) GetAcceptOnlyCa() bool {
	if m != nil {
		return m.AcceptOnlyCa
	}
	return false
}

func (m *LogConfig) GetLogBackendName() string {
	if m != nil {
		return m.LogBackendName
	}
	return ""
}

func (m *LogConfig) GetIsMirror() bool {
	if m != nil {
		return m.IsMirror
	}
	return false
}

func (m *LogConfig) GetDnsZone() string {
	if m != nil {
		return m.DnsZone
	}
	return ""
}

// LogMultiConfig wraps up a LogBackendSet and corresponding LogConfigSet so
// that they can easily be parsed as a single proto.
type LogMultiConfig struct {
	// The set of backends that this configuration will use to send requests to.
	// The names of the backends in the LogBackendSet must all be distinct.
	Backends *LogBackendSet `protobuf:"bytes,1,opt,name=backends,proto3" json:"backends,omitempty"`
	// The set of logs that will use the above backends. All the protos in this
	// LogConfigSet must set a valid log_backend_name for the config to be usable.
	LogConfigs           *LogConfigSet `protobuf:"bytes,2,opt,name=log_configs,json=logConfigs,proto3" json:"log_configs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *LogMultiConfig) Reset()         { *m = LogMultiConfig{} }
func (m *LogMultiConfig) String() string { return proto.CompactTextString(m) }
func (*LogMultiConfig) ProtoMessage()    {}
func (*LogMultiConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_config_6fd5b9e353af6845, []int{4}
}
func (m *LogMultiConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogMultiConfig.Unmarshal(m, b)
}
func (m *LogMultiConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogMultiConfig.Marshal(b, m, deterministic)
}
func (dst *LogMultiConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogMultiConfig.Merge(dst, src)
}
func (m *LogMultiConfig) XXX_Size() int {
	return xxx_messageInfo_LogMultiConfig.Size(m)
}
func (m *LogMultiConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_LogMultiConfig.DiscardUnknown(m)
}

var xxx_messageInfo_LogMultiConfig proto.InternalMessageInfo

func (m *LogMultiConfig) GetBackends() *LogBackendSet {
	if m != nil {
		return m.Backends
	}
	return nil
}

func (m *LogMultiConfig) GetLogConfigs() *LogConfigSet {
	if m != nil {
		return m.LogConfigs
	}
	return nil
}

func init() {
	proto.RegisterType((*LogBackend)(nil), "configpb.LogBackend")
	proto.RegisterType((*LogBackendSet)(nil), "configpb.LogBackendSet")
	proto.RegisterType((*LogConfigSet)(nil), "configpb.LogConfigSet")
	proto.RegisterType((*LogConfig)(nil), "configpb.LogConfig")
	proto.RegisterType((*LogMultiConfig)(nil), "configpb.LogMultiConfig")
}

func init() { proto.RegisterFile("config.proto", fileDescriptor_config_6fd5b9e353af6845) }

var fileDescriptor_config_6fd5b9e353af6845 = []byte{
	// 606 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x52, 0x4d, 0x6f, 0x13, 0x3b,
	0x14, 0x55, 0x5e, 0xda, 0x34, 0xb9, 0xf9, 0x78, 0xef, 0x19, 0xda, 0x4e, 0xcb, 0x82, 0x10, 0x81,
	0x14, 0x09, 0x69, 0x82, 0x5a, 0x15, 0x16, 0x2c, 0x50, 0x5b, 0x81, 0x40, 0x4d, 0xa1, 0x9a, 0xc0,
	0x86, 0x8d, 0x35, 0x1f, 0x37, 0x53, 0x53, 0x8f, 0x3d, 0xb2, 0x9d, 0x2a, 0xc3, 0x82, 0x9f, 0xca,
	0x6f, 0x41, 0x63, 0x7b, 0x5a, 0x15, 0xba, 0x60, 0x35, 0xbe, 0xf7, 0x9c, 0x73, 0xe7, 0xd8, 0xf7,
	0xc0, 0x20, 0x95, 0x62, 0xc9, 0xf2, 0xb0, 0x54, 0xd2, 0x48, 0xd2, 0x75, 0x55, 0x99, 0xec, 0x1f,
	0xe5, 0xcc, 0x5c, 0xae, 0x92, 0x30, 0x95, 0xc5, 0x2c, 0x97, 0x32, 0xe7, 0x38, 0x33, 0x8a, 0x71,
	0xce, 0x62, 0x31, 0x4b, 0x55, 0x55, 0x1a, 0x39, 0xbb, 0xc2, 0x4a, 0x97, 0x89, 0xff, 0xb8, 0x01,
	0xfb, 0x7b, 0x9e, 0x6b, 0xab, 0x64, 0xb5, 0x9c, 0xc5, 0xa2, 0xf2, 0xd0, 0xe3, 0xdf, 0x21, 0xc3,
	0x0a, 0xd4, 0x26, 0x2e, 0x4a, 0x47, 0x98, 0x9c, 0x02, 0xcc, 0x65, 0x7e, 0x12, 0xa7, 0x57, 0x28,
	0x32, 0x42, 0x60, 0x43, 0xc4, 0x05, 0x06, 0xad, 0x71, 0x6b, 0xda, 0x8b, 0xec, 0x99, 0x3c, 0x81,
	0x41, 0xe2, 0x60, 0xaa, 0x4b, 0x4c, 0x83, 0x7f, 0x2c, 0xd6, 0xf7, 0xbd, 0x45, 0x89, 0xe9, 0xe4,
	0x0d, 0x0c, 0x6f, 0x87, 0x2c, 0xd0, 0x90, 0x10, 0xb6, 0x3c, 0x1e, 0xb4, 0xc6, 0xed, 0x69, 0xff,
	0xe0, 0x61, 0xd8, 0x5c, 0x32, 0xbc, 0x65, 0x46, 0x0d, 0x69, 0xf2, 0x1a, 0x06, 0x73, 0x99, 0x9f,
	0x5a, 0x4a, 0xad, 0x7f, 0x0e, 0x1d, 0xc7, 0xf7, 0xf2, 0x07, 0x77, 0xe4, 0x8e, 0x17, 0x79, 0xca,
	0xe4, 0xe7, 0x06, 0xf4, 0x6e, 0xba, 0x64, 0x1b, 0x3a, 0x5c, 0xe6, 0x94, 0x65, 0xf6, 0x12, 0xed,
	0x68, 0x93, 0xcb, 0xfc, 0x43, 0x46, 0x76, 0xa0, 0x53, 0x2a, 0x5c, 0xb2, 0xb5, 0xf7, 0xef, 0x2b,
	0xf2, 0x12, 0x76, 0xe5, 0x35, 0x2a, 0xc5, 0x32, 0xa4, 0x97, 0xb1, 0xc8, 0x38, 0x2a, 0xea, 0x89,
	0x43, 0x4b, 0xdc, 0x6e, 0xe0, 0xf7, 0x0e, 0xbd, 0x70, 0xba, 0xa7, 0x30, 0x52, 0x52, 0x1a, 0x4d,
	0x4b, 0x2c, 0xe8, 0x92, 0x71, 0x0c, 0xda, 0xe3, 0xf6, 0xb4, 0x17, 0x0d, 0x6c, 0xf7, 0x02, 0x8b,
	0x77, 0x8c, 0x23, 0x39, 0x82, 0x7e, 0xa9, 0xd8, 0x75, 0x6c, 0x90, 0x5e, 0x61, 0x15, 0x6c, 0x8c,
	0x5b, 0xf6, 0x2d, 0xdc, 0x52, 0xc2, 0x66, 0x29, 0xe1, 0xb1, 0xa8, 0x22, 0xf0, 0xc4, 0x33, 0xac,
	0xc8, 0x0b, 0x80, 0x72, 0x95, 0x70, 0x96, 0x5a, 0xd5, 0xa6, 0x55, 0xfd, 0x1f, 0xfa, 0x9d, 0x5f,
	0x58, 0xe4, 0x0c, 0xab, 0xa8, 0x57, 0x36, 0x47, 0xf2, 0x0c, 0x46, 0x0a, 0xbf, 0x61, 0x6a, 0x28,
	0xae, 0x4b, 0xa6, 0x30, 0x0b, 0x3a, 0xe3, 0xd6, 0xb4, 0x1b, 0x0d, 0x5d, 0xf7, 0xad, 0x6b, 0xd6,
	0xae, 0x71, 0x6d, 0xea, 0xa9, 0x74, 0xa5, 0xe3, 0x1c, 0x75, 0xb0, 0xe5, 0x5c, 0xe3, 0xda, 0x9c,
	0x61, 0xf5, 0xc5, 0xf6, 0xc8, 0x09, 0xfc, 0x2b, 0xa4, 0xa1, 0xf1, 0xd2, 0xa0, 0xa2, 0xda, 0xc4,
	0xca, 0x04, 0x5d, 0xeb, 0x61, 0xff, 0x0f, 0xe7, 0x9f, 0x9b, 0x38, 0x45, 0x43, 0x21, 0xcd, 0x71,
	0xad, 0x58, 0xd4, 0x82, 0xbb, 0x33, 0x38, 0x2b, 0x98, 0x09, 0x7a, 0x7f, 0x3f, 0x63, 0x5e, 0x0b,
	0x6a, 0xb7, 0x71, 0x9a, 0x62, 0x69, 0xa8, 0x14, 0xbc, 0xa2, 0x69, 0x1c, 0x80, 0xbd, 0xd4, 0xc0,
	0x75, 0x3f, 0x09, 0x5e, 0x9d, 0xc6, 0x64, 0x0a, 0xff, 0xd5, 0x0b, 0x6f, 0x32, 0x6a, 0xf3, 0xdb,
	0xb7, 0xab, 0x1b, 0xf1, 0x9b, 0xa8, 0x7d, 0xac, 0x93, 0xfc, 0x08, 0x7a, 0x4c, 0xd3, 0x82, 0x29,
	0x25, 0x55, 0x30, 0xb0, 0xa3, 0xba, 0x4c, 0x9f, 0xdb, 0x9a, 0xec, 0x41, 0x37, 0x13, 0x9a, 0x7e,
	0x97, 0x02, 0x83, 0x91, 0x95, 0x6f, 0x65, 0x42, 0x7f, 0x95, 0x02, 0x27, 0x3f, 0x60, 0x34, 0x97,
	0xf9, 0xf9, 0x8a, 0x1b, 0xe6, 0x43, 0x76, 0x08, 0x5d, 0xff, 0x3f, 0x6d, 0x63, 0xd6, 0x3f, 0xd8,
	0xbd, 0x2f, 0xe0, 0x0b, 0x34, 0xd1, 0x0d, 0x91, 0xbc, 0x82, 0x7e, 0x6d, 0xd4, 0xf1, 0xb4, 0xcd,
	0x61, 0xff, 0x60, 0xe7, 0x9e, 0x64, 0xd7, 0x32, 0xe0, 0x4d, 0xa5, 0x93, 0x8e, 0x7d, 0xaa, 0xc3,
	0x5f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x93, 0xdd, 0x9e, 0x02, 0x37, 0x04, 0x00, 0x00,
}
