apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: trillian-ctfe-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: trillian-ctfe-global-static-ip
spec:
  defaultBackend:
    service:
      name: trillian-ctfe-service
      port: 
        number: 6962
