apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: trillian-ctfe
  name: trillian-ctfe
spec:
  type: LoadBalancer
  ports:
  - name: "80"
    port: 80
    targetPort: 6962
  selector:
    io.kompose.service: trillian-ctfe
status:
  loadBalancer: {}
