// Code generated by "stringer -type=LogStatus"; DO NOT EDIT.

package loglist2

import "strconv"

const _LogStatus_name = "UndefinedLogStatusPendingLogStatusQualifiedLogStatusUsableLogStatusReadOnlyLogStatusRetiredLogStatusRejectedLogStatus"

var _LogStatus_index = [...]uint8{0, 18, 34, 52, 67, 84, 100, 117}

func (i LogStatus) String() string {
	if i < 0 || i >= LogStatus(len(_LogStatus_index)-1) {
		return "LogStatus(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _LogStatus_name[_LogStatus_index[i]:_LogStatus_index[i+1]]
}
