// Code generated by "stringer -type=LogStatus"; DO NOT EDIT.

package loglist2

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[UndefinedLogStatus-0]
	_ = x[RejectedLogStatus-1]
	_ = x[RetiredLogStatus-2]
	_ = x[ReadOnlyLogStatus-3]
	_ = x[PendingLogStatus-4]
	_ = x[QualifiedLogStatus-5]
	_ = x[UsableLogStatus-6]
}

const _LogStatus_name = "UndefinedLogStatusRejectedLogStatusRetiredLogStatusReadOnlyLogStatusPendingLogStatusQualifiedLogStatusUsableLogStatus"

var _LogStatus_index = [...]uint8{0, 18, 35, 51, 68, 84, 102, 117}

func (i LogStatus) String() string {
	if i < 0 || i >= LogStatus(len(_LogStatus_index)-1) {
		return "LogStatus(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _LogStatus_name[_LogStatus_index[i]:_LogStatus_index[i+1]]
}
